CREATE TABLE ITEM_Type
(
	Type_ID int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	Type_Name varchar(40)
);

INSERT INTO ITEM_Type
	(Type_Name)
VALUES
	('Poké Balls'),
	('HP Restorative'),
	('Status Condition Healing Item'),
	('PP Restorative'),
	('Drink'),
	('Herbal Medicine'),
	('Ether'),
	('Vitamin'),
	('Battle Item'),
	('Escape Item'),
	('Flute'),
	('Valuable Item'),
	('Shard'),
	('Repel'),
	('Evolutionary Stone'),
	('Mulch'),
	('Fossil'),
	('Evolution-inducing Held Item'),
	('Legendary Artifact'),
	('Mail'),
	('Berrries');


CREATE TABLE ITEM_Data
(
	Item_ID int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	Item_Name varchar(20) NOT NULL,
	Item_Type int DEFAULT 0
);

INSERT INTO ITEM_Data
	(Item_Name, Item_Type)
VALUES
	('Master Ball', 1),
	('Ultra Ball', 1),
	('Great Ball', 1),
	('Poké Ball', 1),
	('Safari Ball', 1),
	('Net Ball', 1),
	('Dive Ball', 1),
	('Nest Ball', 1),
	('Repeat Ball', 1),
	('Timer Ball', 1),
	('Luxury Ball', 1),
	('Premier Ball', 1),
	('Dusk Ball', 1),
	('Heal Ball', 1),
	('Quick Ball', 1),
	('Cherish Ball', 1),
	('Potion', 2),
	('Antidote', 3),
	('Burn Heal', 3),
	('Ice Heal', 3),
	('Awakening', 3),
	('Paralyze Heal', 3),
	('Full Restore', 2),
	('Max Potion', 2),
	('Hyper Potion', 2),
	('Super Potion', 2),
	('Full Heal', 3),
	('Revive', 4),
	('Max Revive', 4),
	('Fresh Water', 5),
	('Soda Pop', 5),
	('Lemonade', 5),
	('Moomoo Milk', 5),
	('Energy Powder', 6),
	('Energy Root', 6),
	('Heal Powder', 6),
	('Revival Herb', 6),
	('Ether', 7),
	('Max Ether', 7),
	('Elixir', 7),
	('Max Elixir', 7),
	('Lava Cookie', 3),
	('Berry Juice', 5),
	('Sacred Ash', 4),
	('HP Up', 8),
	('Protein', 8),
	('Iron', 8),
	('Carbos', 8),
	('Calcium', 8),
	('Rare Candy', 8),
	('PP Up', 8),
	('Zinc', 8),
	('PP Max', 8),
	('Old Gateau', 3),
	('Guard Spec.', 9),
	('Dire Hit', 9),
	('X Attack', 9),
	('X Defense', 9),
	('X Speed', 9),
	('X Accuracy', 9),
	('X Sp. Atk', 9),
	('X Sp. Def', 9),
	('Poké Doll', 10),
	('Fluffy Tail', 10),
	('Blue Flute', 11),
	('Yellow Flute', 11),
	('Red Flute', 11),
	('Black Flute', 11),
	('White Flute', 11),
	('Shoal Salt', 12),
	('Shoal Shell', 12),
	('Red Shard', 13),
	('Blue Shard', 13),
	('Yellow Shard', 13),
	('Green Shard', 13),
	('Super Repel', 14),
	('Max Repel', 14),
	('Escape Rope', 0),
	('Repel', 14),
	('Sun Stone', 15),
	('Moon Stone', 15),
	('Fire Stone', 15),
	('Thunder Stone', 15),
	('Water Stone', 15),
	('Leaf Stone', 15),
	('Tiny Mushroom', 12),
	('Big Mushroom', 12),
	('Pearl', 12),
	('Big Pearl', 12),
	('Stardust', 12),
	('Star Piece', 12),
	('Nugget', 12),
	('Heart Scale', 12),
	('Honey', 0),
	('Growth Mulch', 16),
	('Damp Mulch', 16),
	('Stable Mulch', 16),
	('Gooey Mulch', 16),
	('Root Fossil', 17),
	('Claw Fossil', 17),
	('Helix Fossil', 17),
	('Dome Fossil', 17),
	('Old Amber', 17),
	('Armor Fossil', 17),
	('Skill Fossil', 17),
	('Rare Bone', 12),
	('Shiny Stone', 15),
	('Dusk Stone', 15),
	('Dawn Stone', 15),
	('Oval Stone', 18),
	('Odd Keystone', 0),
	('Griseous Orb', 19),
	('Douse Drive', 19),
	('Shock Drive', 19),
	('Burn Drive', 19),
	('Chill Drive' 19),
	('Sweet Heart', 2),
	('Adamant Orb', 19),
	('Lustrous Orb', 19),
	('Greet Mail', 20),
	('Favored Mail', 20),
	('RSVP Mail', 20),
	('Thanks Mail', 20),
	('Inquiry Mail', 20),
	('Like Mail', 20),
	('Reply Mail', 20),
	('Bridge Mail S', 20),
	('Bridge Mail D', 20),
	('Bridge Mail T', 20),
	('Bridge Mail V', 20),
	('Bridge Mail M', 20),
